hw_03
Shaydaeva/Basics-Django pull request #2
Opened 2020-12-13 20:24 UTC by Shaydaeva

Сделала 3 практическое задание, вроде получилось))
Имитацию перехода по категориям тоже сделала, если это имелось в виду, долго не получалось, а потом заработало))

2020-12-14 10:50 UTC, Vokler requested changes

2020-12-14 10:50 UTC, Vokler commented on .gitignore
> +requirements.txt
Не стоит добавлять этот файл сюда, так как он необходим для загрузки необходимых пакетов.
Представьте, что кто-то скачал ваше репозиторий и он не знает, какие пакеты нужно установить, поэтому он просто прописывает `pip install -r requirements.txt` и все нужные пакеты установились.

2020-12-14 21:41 UTC, Shaydaeva commented on .gitignore
> +requirements.txt
Поправила

2020-12-16 14:24 UTC, Vokler approved these changes

2020-12-16 14:24 UTC, merged